import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import { Header } from '@/src/common/components/Header';

// const inter = Inter({ subsets: ['latin'] });
import '@/src/styles/index.css';

export const metadata: Metadata = {
    title: 'Money App',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="antialiased max-w-screen-xl w-full">
                <div className="flex flex-col justify-between py-10 px-6 h-screen">
                    <Header />
                    {children}
                </div>
            </body>
        </html>
    );
}

